### ISSUE TITLE
Newer firmware files

### ISSUE THREAD

**Issue by stefan-langenmaier** [pH5/coda-bits#1]
Hello!

I just saw that there are newer firmware files up to version 7.9:
https://www.nxp.com/lgfiles/NMG/MAD/YOCTO/firmware-imx-7.9.bin
Just in case you haven't checked it and you want to version bump your documentation.

Thanks for your work and this awesome repo!
Best regards,
Stefan

**Comment by pH5** [comment]
Thank you, bumped. There have been no further changes to the CODA firmware files, though.
